"Quotes File"

quotes = [
    "'The only way to do great work is to love what you do.' - Steve Jobs",
    "'Code is like humor. When you have to explain it, it's bad.' - Cory House",
    "'First, solve the problem. Then, write the code.' - John Johnson",
    "'Talk is cheap. Show me the code.' - Linus Torvalds",
    "'The best error message is the one that never shows up.' - Thomas Fuchs",
    "'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.' - Martin Fowler",
    "'Experience is the name everyone gives to their mistakes.' - Oscar Wilde",
    "'In order to be irreplaceable, one must always be different.' - Coco Chanel",
    "'Java is to JavaScript what car is to Carpet.' - Chris Heilmann",
    "'Knowledge is power.' - Francis Bacon",
    "'Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.' - Dan Salomon",
    "'Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.' - Antoine de Saint-Exupery",
    "'Before software can be reusable it first has to be usable.' - Ralph Johnson",
    "'Make it work, make it right, make it fast.' - Kent Beck",
    "'Simplicity is the soul of efficiency.' - Austin Freeman",
    "'Fix the cause, not the symptom.' - Steve Maguire",
    "'Optimism is an occupational hazard of programming: feedback is the treatment.' - Kent Beck",
    "'Walking on water and developing software from a specification are easy if both are frozen.' - Edward V Berard",
    "'It's not a bug – it's an undocumented feature.' - Anonymous",
    "'The most important property of a program is whether it accomplishes the intention of its user.' - C.A.R. Hoare",
    "'Programs must be written for people to read, and only incidentally for machines to execute.' - Harold Abelson",
    "'Controlling complexity is the essence of computer programming.' - Brian Kernighan",
    "'The function of good software is to make the complex appear to be simple.' - Grady Booch",
    "'Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.' - Linus Torvalds",
    "'The best way to predict the future is to invent it.' - Alan Kay",
    "'You are in danger of living a life so comfortable and soft, that you will die without ever realizing your true potential.' - David Goggins",
    "'I don't stop when I'm tired. I stop when I'm done.' - David Goggins",
    "'We’re either getting better or we’re getting worse.' - David Goggins",
    "'We don’t rise to the standards we have when others are watching; we fall to the standards we have when no one is.' - Alex Hormozi",
    "'Work like your life depends on it. Because it does.' - Alex Hormozi",
]
